version: '3.7'
services:  
  GoodMorning:
    image: goodmorning
    container_name: goodmorning
    depends_on:
      - "redis_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    env_file:
      - .env
    links:
      - "redis_image"  

  redis_image:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
      
